//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLRapPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChieu()
        {
            this.GheNgois = new HashSet<GheNgoi>();
        }
    
        public string id { get; set; }
        public string idPhim { get; set; }
        public string idCaChieu { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public string idPhong { get; set; }
    
        public virtual CaChieu CaChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GheNgoi> GheNgois { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
    }
}
