//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLRapPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public string id { get; set; }
        public Nullable<int> LoaiVe { get; set; }
        public string idGheNgoi { get; set; }
        public string idKhachHang { get; set; }
        public Nullable<decimal> TienBanVe { get; set; }
        public string Ghe { get; set; }
    
        public virtual GheNgoi GheNgoi { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiVe LoaiVe1 { get; set; }
    }
}
